---
output:
  html_document:
    df_print: paged
  pdf_document: default
header-includes:
- \usepackage{caption}
- \captionsetup[figure]{labelformat=empty}
---
\captionsetup[table]{labelformat=empty}
```{r setup, echo = FALSE, message = FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
library(tidyverse)
library(brms)
library(cowplot)
library(knitr)
library(kableExtra)

predicted_consumption <- readRDS("../output/02_posterior_predictive_mass_load.rds") %>%
  ungroup() %>%
  filter(mass_load_missing == 0) %>%
  group_by(metabolite, time_pretty, location) %>%
  summarise(median_mass_load = quantile(mass_load, probs = 0.5, na.rm = FALSE),
            low_mass_load = quantile(mass_load, probs = 0.25, na.rm = FALSE),
            high_mass_load = quantile(mass_load, probs = 0.75, na.rm = FALSE),
  )
```

```{r}
predicted_consumption %>% 
  mutate(statistic = paste0(prettyNum(round(median_mass_load, digits = 1), big.mark = ","), " (", prettyNum(round(low_mass_load , digits = 1), big.mark = ","), ", ", prettyNum(round(high_mass_load, digits = 1), big.mark = ","), ")", sep = "")) %>%
  select(metabolite, time_pretty, location, statistic) %>% 
  spread(location, statistic) %>%
  group_by(metabolite) %>%
  mutate(group = row_number()) %>%
  ungroup() %>%
  mutate(metabolite = factor(metabolite) %>% fct_relevel("Oxycodone", "Norhydrocodone", "Hydrocodone", "Noroxycodone", "Phentermine", "Cocaine", "Benzoylecgonine", "Amphetamine", "Tramadol", "Pseudoephedrine")) %>%
  arrange(metabolite, time_pretty) %>%
  mutate(metabolite = as.character(metabolite)) %>%
  mutate(metabolite = if_else(group == 1, metabolite, "")) %>%
  rename(Metabolite = metabolite, Time = time_pretty) %>%
  select(-group) %>%
  kable(booktabs = TRUE, longtable = TRUE, caption = "Table S3. Median and interquartile range of estimated mass loads (mg) of substances that passed through given location over previous 30 minutes") %>%
  kable_styling(latex_options = c("repeat_header"))
```

