---
title: "Estimate dose per person"
author: "Matthew Shane Loop, PhD"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(knitr)
library(tidyverse)
library(brms)
water <- read_tsv("../data/water_cleaned.txt") %>% mutate_if(is.character, ~na_if(., "")) %>%
  mutate(time_pretty = as.character(time_pretty)) %>%
  group_by(metabolite) %>%
  mutate(non_missing = if_else(is.na(value) == FALSE, 1, 0),
         total_non_missing = sum(non_missing)) %>%
  filter(total_non_missing > 50) %>%
  mutate(censored_value = if_else(is.na(value) == TRUE, lloq, 
                                  if_else(value < lloq, lloq,
                                          if_else(value > uloq, uloq, value)
                                          )
                                  ),
         log_value = log(censored_value),
         censored = if_else(censored_value == lloq, "left",
                      if_else(censored_value == uloq, "right", "none"))
  )
metabolite_info <- read_tsv("03_metabolism_data.txt")
flow <- read_tsv("../data/flow_rate.txt") %>%
  mutate(time_pretty = as.character(time_pretty),
         flow_rate_gallons_per_day = flow_rate * 1e6,
         flow_rate_liters_per_day = flow_rate_gallons_per_day * 3.78541)
```


Load models, find posterior predictive checks, and combine all into one dataset.
```{r}
load(file = "02_model_metabolites_censored_amphetamine.RData")
load(file = "02_model_metabolites_censored_benzoylecgonine.RData")
load(file = "02_model_metabolites_censored_cocaine.RData")
load(file = "02_model_metabolites_censored_hydrocodone.RData")
load(file = "02_model_metabolites_censored_norhydrocodone.RData")
load(file = "02_model_metabolites_censored_oxycodone.RData")
load(file = "02_model_metabolites_censored_phentermine.RData")
load(file = "02_model_metabolites_censored_pseudoephedrine.RData")
load(file = "02_model_metabolites_censored_tramadol.RData")

results <- tibble(models = list(fit_amphetamine, fit_benzo, fit_cocaine, fit_hydrocodone, fit_norhydrocodone, fit_oxycodone, fit_phentermine, fit_pseudoephedrine, fit_tramadol)) %>%
  mutate(
    metabolite = c("Amphetamine", "Benzoylecgonine", "Cocaine", "Hydrocodone", "Norhydrocodone", "Oxycodone", "Phentermine", "Pseudoephedrine", "Tramadol")
  )
```


```{r}
predicted_consumption <- results %>%
  group_by(metabolite) %>%
  mutate(
    posterior_predictions = map2(models, metabolite, ~posterior_predict(.x, re_formula = ~(1 | location)) %>%
                                  t() %>%
                                  as_tibble() %>%
                                  bind_cols(filter(water, metabolite == .y), .) %>%
                                   group_by(time_pretty, location) %>%
                                  slice(1) %>%
                                  ungroup() %>%
                                  dplyr::select(time_pretty, location, V1:V12000) %>%
                                  gather(iteration, mean_log_conc, -time_pretty, -location) %>%
                                  mutate(
                                    mean_concentration = exp(mean_log_conc) * 1000,  # original data reported as ng/mL; convert to liters for mass load calculations
                                    metabolite = .y
                                  ) %>%
                                  left_join(., metabolite_info, by = "metabolite") %>%
                                  left_join(., flow, by = "time_pretty") %>%
                                  mutate(
                                    mass_load = mean_concentration * flow_rate_liters_per_day * (100 / (100 + stability)) * 1e-6,
                                    consumption_per_1000 = mass_load * 100 * (1 / excretion) * mwpar_mwmet * 1000 / 80651 / typical_dose_mg, # unit is doses per 1000
                                  consumption_missing = if_else(is.na(consumption_per_1000) == TRUE, 1, 0))
                                 ),
    quantiles_predictions = map(posterior_predictions, ~group_by(., location, time_pretty) %>%
                                  filter(consumption_missing == 0) %>%
                                  summarise(
                                    median_mean_consumption = median(consumption_per_1000),
                                    low_mean_consumption = quantile(consumption_per_1000, probs = 0.25),
                                    high_mean_consumption = quantile(consumption_per_1000, probs = 0.75),
                                  )
                                ),
    plots = map2(quantiles_predictions, metabolite, ~ggplot(data = .x, aes(x = time_pretty, y = median_mean_consumption, color = factor(location))) +
  geom_pointrange(aes(ymin = low_mean_consumption, ymax = high_mean_consumption), position = position_dodge(0.8)) +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1)
  ) +
  scale_color_viridis_d(name = "Location") +
  labs(
    y = "Doses per 1,000 attendees",
    x = "Time of wastewater collection",
    title = .y
  ))
  )
```

```{r, fig.width=14.2, fig.height=7.4, dpi=300}
library(cowplot)
title <- ggdraw() + 
  draw_label(
    "Estimated 25th, 50th, and 75th percentiles of number of doses 1,000 attendees",
    fontface = 'bold',
    x = 0,
    hjust = 0
  ) +
  theme(
    # add margin on the left of the drawing canvas,
    # so title is aligned with left edge of first plot
    plot.margin = margin(0, 0, 0, 7)
  )
plots <- plot_grid(plotlist = predicted_consumption$plots[c(1, 3, 4, 8, 9)])
cowplot::plot_grid(title, plots, ncol = 1, rel_heights = c(1, 9)) -> p
p
ggsave(filename = "02_estimate_dosage_censored.png", p)
```

## Estimate, averaging across all locations
```{r}
predicted_consumption_overall <- results %>%
  group_by(metabolite) %>%
  mutate(
    posterior_predictions = map2(models, metabolite, ~posterior_predict(.x, re_formula = NA) %>%
                                  t() %>%
                                  as_tibble() %>%
                                  bind_cols(filter(water, metabolite == .y), .) %>%
                                   group_by(time_pretty) %>%
                                  slice(1) %>%
                                  ungroup() %>%
                                  dplyr::select(time_pretty, V1:V12000) %>%
                                  gather(iteration, mean_log_conc, -time_pretty) %>%
                                  mutate(
                                    mean_concentration = exp(mean_log_conc) * 1000,  # original data reported as ng/mL; convert to liters for mass load calculations
                                    metabolite = .y
                                  ) %>%
                                  left_join(., metabolite_info, by = "metabolite") %>%
                                  left_join(., flow, by = "time_pretty") %>%
                                  mutate(
                                    mass_load = mean_concentration * flow_rate_liters_per_day * (100 / (100 + stability)) * 1e-6,
                                    consumption_per_1000 = mass_load * 100 * (1 / excretion) * mwpar_mwmet * 1000 / 80651 / typical_dose_mg, # unit is doses per 1000
                                  consumption_missing = if_else(is.na(consumption_per_1000) == TRUE, 1, 0))
                                 ),
    quantiles_predictions = map(posterior_predictions, ~group_by(., time_pretty) %>%
                                  filter(consumption_missing == 0) %>%
                                  summarise(
                                    median_mean_consumption = median(consumption_per_1000),
                                    low_mean_consumption = quantile(consumption_per_1000, probs = 0.25),
                                    high_mean_consumption = quantile(consumption_per_1000, probs = 0.75),
                                  )
                                ),
    plots = map2(quantiles_predictions, metabolite, ~ggplot(data = .x, aes(x = time_pretty, y = median_mean_consumption)) +
  geom_pointrange(aes(ymin = low_mean_consumption, ymax = high_mean_consumption), position = position_dodge(0.8)) +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1)
  ) +
  labs(
    y = "Doses per 1,000 attendees",
    x = "Time of wastewater collection",
    title = .y
  ))
  )
```

```{r, fig.width=14.2, fig.height=7.4, dpi=300}
library(cowplot)
title <- ggdraw() + 
  draw_label(
    "Estimated 25th, 50th, and 75th percentiles of number of doses 1,000 attendees",
    fontface = 'bold',
    x = 0,
    hjust = 0
  ) +
  theme(
    # add margin on the left of the drawing canvas,
    # so title is aligned with left edge of first plot
    plot.margin = margin(0, 0, 0, 7)
  )
plots <- plot_grid(plotlist = predicted_consumption_overall$plots[c(1, 3, 4, 8, 9)])
cowplot::plot_grid(title, plots, ncol = 1, rel_heights = c(1, 9)) -> p
p
ggsave(filename = "02_estimate_dosage_censored_overall.png", p)
```

## Estimate overall, averaged across all times
```{r, fig.width=10, fig.height=5}
predicted_consumption_overall %>%
  unnest(posterior_predictions) %>%
  ungroup() %>%
  group_by(metabolite) %>%
  filter(consumption_missing == 0) %>%
  summarise(median_mean_consumption = median(consumption_per_1000),
            low_mean_consumption = quantile(consumption_per_1000, probs = 0.25),
            high_mean_consumption = quantile(consumption_per_1000, probs = 0.75),
  ) %>%
  ggplot(aes(x = metabolite, y = median_mean_consumption)) +
  geom_pointrange(aes(ymin = low_mean_consumption, ymax = high_mean_consumption)) +
  labs(
    y = "Doses per 1,000 attendees",
    x = "Time of wastewater collection",
    title = "Estimated 25th, 50th, and 75th percentiles of number of doses 1,000 attendees"
  ) -> p
p
ggsave(filename = "02_estimate_dosage_censored_grand.png", p, dpi = 300)
```

