---
output: html_document
---

```{r setup, echo = FALSE, message = FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
library(tidyverse)
library(brms)
library(cowplot)
library(htmlTable)

predicted_consumption <- readRDS("../output/02_posterior_predictive_mass_load.rds") %>%
  ungroup() %>%
  filter(mass_load_missing == 0) %>%
  group_by(metabolite, iteration, machine, extraction) %>%
  summarise(whole_game_stadium_mass_load = sum(mass_load)) %>%
  group_by(metabolite) %>%
  summarise(median_mass_load = quantile(whole_game_stadium_mass_load, probs = 0.5, na.rm = FALSE),
            low_mass_load = quantile(whole_game_stadium_mass_load, probs = 0.25, na.rm = FALSE),
            high_mass_load = quantile(whole_game_stadium_mass_load, probs = 0.75, na.rm = FALSE),
  )
```

```{r}
predicted_consumption %>% 
  mutate(statistic = paste0(prettyNum(round(median_mass_load, digits = 2), big.mark = ","), " (", prettyNum(round(low_mass_load , digits = 2), big.mark = ","), ", ", prettyNum(round(high_mass_load, digits = 2), big.mark = ","), ")", sep = ""),
         statistic_per_1000 = paste0(prettyNum(round(median_mass_load / 80.651, digits = 2), big.mark = ","), " (", prettyNum(round(low_mass_load / 80.651, digits = 2), big.mark = ","), ", ", prettyNum(round(high_mass_load / 80.651, digits = 2), big.mark = ","), ")", sep = "")) %>%
  select(metabolite, statistic, statistic_per_1000) %>% 
  mutate(metabolite = factor(metabolite) %>% fct_relevel("Oxycodone", "Norhydrocodone", "Hydrocodone", "Noroxycodone", "Phentermine", "Cocaine", "Benzoylecgonine", "Amphetamine", "Tramadol", "Pseudoephedrine")) %>%
  arrange(metabolite) %>%
  rename(Metabolite = metabolite, `Mass load (mg)` = statistic, `Mass load per 1,000 attendees (mg)` = statistic_per_1000) %>%
  htmlTable::htmlTable(caption = "Table 1. Median and interquartile range of estimated mass loads (mg) of substances that passed through the entire stadium over the course of the game", rnames = FALSE)
```

