---
title: "simulation_new"
author: "amanda li"
date: "2/4/2020"
output: html_document
---
# !diagnostics off
```{r setup, include=FALSE}


library(rms)
library(tidyverse)
library(MASS)
library(truncnorm)
library(data.table)
library(tidyverse)
library(tidystats)
library(VIM)
library(randomForestSRC)
```

```{r}
data<-read.csv(file="tramadol.csv",header = T,sep = ",")
value<-data.frame(value=data$value)

value
```


```{r}
set.seed(123)
a <- rnorm(10, 0, 2)      
                                  
b<-rnorm(3, 0, 2)

time<-vector(length = 30)

location<-vector(length = 30)

for (j in 1:3) {
  for (i in 1:10) {
  
    time[10*(j-1)+i]=a[i]
    location[10*(j-1)+i]=b[j]
  }
}

time_ind<-rep(1:10,3)
location_ind<-c(rep(1,10),rep(2,10),rep(3,10))



mu_ij=tibble(time=time,location=location,mu=rep(2.5),time_ind=time_ind,location_ind=location_ind,mu_ij=location+time+mu)


```


```{r}
simulation_store<-list()
for (i in 1:30) {
  number_of_iterations <- 10


  simulated_data = tribble(
  ~iteration,
  seq(1, number_of_iterations, 1)
) %>%
  unnest(iteration) %>%
  group_by(iteration) %>%
  nest() %>%
  mutate(
    n = 3,  # The sample size can be uncertain, based upon recruiting or dropout. Choosing sample size randomly can be an interesting way to incorporate your uncertainty about the final study results.
   
     
    
    
     fake_data = map(n, ~tibble(  
                                 
                                 tramadol = rtruncnorm(., a=0, b=Inf, mean = mu_ij$mu_ij[i], sd = 11.5),
                                
                                  
                                  
                                
                                   # How does linear predictor depend upon covariate(s)?
                                  id = seq(1, ., 1)) %>%
                              group_by(id) %>%  # Need to group by ID in order to simulate a single random variable for each observation
                              mutate(y = rbinom(1, size = 1, prob = arm::invlogit(tramadol)))
    )
  ) %>%dplyr::select(-data)

   #name1<-paste("simulated_data_1",sep ="_",i,".csv")

   #write.table(simulated_data$fake_data[[1]],file=name1,sep = ",",col.names = T,row.names = F)
  
  
  simulation_store[[i]]<-simulated_data[[3]]
  
  
  
}



list_tramadol<-data.frame(matrix(NA,nrow = 90,ncol = 10))

list_name=c()
for (i in 1:number_of_iterations) {
  name<-paste("group",sep ="_",i)
  list_name[i]<-name
  names(list_tramadol)<-list_name
}
  
b<-vector(mode = "list",30)


for (h in 1:number_of_iterations) {
  

 for (i in 1:30) {
  
    
   b[[i]]<-simulation_store[[i]][[h]]
   

    
 }
  
  
   list_tramadol[,h]<-rbindlist(b)[,1]

}

id<-matrix(NA,nrow = 3,ncol=30 )
for (i in 1:30) {
  
  id[1:3,i]<-rep(i,3)
}

time_index<-rep(c(rep(1,3),rep(2,3),rep(3,3),rep(4,3),rep(5,3),rep(6,3),rep(7,3),rep(8,3),rep(9,3),rep(10,3)),3)
location_index<-c(rep(1,30),rep(2,30),rep(3,30))



u_ij<-as.vector(id)
 list_tramadol<-cbind(u_ij,time_index,location_index,list_tramadol)
 
list_tramadol_10<-as.data.frame(list_tramadol[,9])
list_tramadol_20<-as.data.frame(list_tramadol[,10])
list_tramadol_30<-as.data.frame(list_tramadol[,11])
list_tramadol_40<-as.data.frame(list_tramadol[,12])
list_tramadol_50<-as.data.frame(list_tramadol[,13])

list_tramadol_control<-as.data.frame(list_tramadol[,4:8])
```




```{r}

list_tramadol_10.missing_MCAR<- produce_NA(list_tramadol_10, mechanism="MCAR", perc.missing = 0.1)$data.incomp

list_tramadol_20.missing_MCAR<- produce_NA(list_tramadol_20, mechanism="MCAR", perc.missing = 0.2)$data.incomp

list_tramadol_30.missing_MCAR<- produce_NA(list_tramadol_30, mechanism="MCAR", perc.missing = 0.3)$data.incomp

list_tramadol_40.missing_MCAR<- produce_NA(list_tramadol_40, mechanism="MCAR", perc.missing = 0.4)$data.incomp

list_tramadol_50.missing_MCAR<- produce_NA(list_tramadol_50, mechanism="MCAR", perc.missing = 0.5)$data.incomp


list_tramadol.missing_MCAR<-cbind(list_tramadol_10.missing_MCAR,list_tramadol_20.missing_MCAR,list_tramadol_30.missing_MCAR,list_tramadol_40.missing_MCAR,list_tramadol_50.missing_MCAR)


name<-c("10% missing","20% missing","30% missing","40% missing","50% missing")
names(list_tramadol.missing_MCAR)<-name

matrixplot(list_tramadol.missing_MCAR, cex.axis = 0.5, interactive = F)
```






```{r}
list_tramadol_10.missing_MCAR_2<- produce_NA(list_tramadol[,9:13], mechanism="MCAR", perc.missing = 0.1,seed = 123)$data.incomp

list_tramadol_20.missing_MCAR_2<- produce_NA(list_tramadol[,9:13], mechanism="MCAR", perc.missing = 0.2,seed = 123)$data.incomp

list_tramadol_30.missing_MCAR_2<- produce_NA(list_tramadol[,9:13], mechanism="MCAR", perc.missing = 0.3,seed = 123)$data.incomp

list_tramadol_40.missing_MCAR_2<- produce_NA(list_tramadol[,9:13], mechanism="MCAR", perc.missing = 0.4,seed = 123)$data.incomp

list_tramadol_50.missing_MCAR_2<- produce_NA(list_tramadol[,9:13], mechanism="MCAR", perc.missing = 0.5,seed = 123)$data.incomp


matrixplot(list_tramadol_10.missing_MCAR_2, cex.axis = 0.5, interactive = F)

matrixplot(list_tramadol_20.missing_MCAR_2, cex.axis = 0.5, interactive = F)

matrixplot(list_tramadol_30.missing_MCAR_2, cex.axis = 0.5, interactive = F)

matrixplot(list_tramadol_40.missing_MCAR_2, cex.axis = 0.5, interactive = F)

matrixplot(list_tramadol_50.missing_MCAR_2, cex.axis = 0.5, interactive = F)
```
```{r}
list_tramadol_10.missing_MAR_2<- produce_NA(list_tramadol[,9:13], mechanism="MAR", perc.missing = 0.1,seed = 123)$data.incomp

list_tramadol_20.missing_MAR_2<- produce_NA(list_tramadol[,9:13], mechanism="MAR", perc.missing = 0.2,seed = 123)$data.incomp

list_tramadol_30.missing_MAR_2<- produce_NA(list_tramadol[,9:13], mechanism="MAR", perc.missing = 0.3,seed = 123)$data.incomp

list_tramadol_40.missing_MAR_2<- produce_NA(list_tramadol[,9:13], mechanism="MAR", perc.missing = 0.4,seed = 123)$data.incomp

list_tramadol_50.missing_MAR_2<- produce_NA(list_tramadol[,9:13], mechanism="MAR", perc.missing = 0.5,seed = 123)$data.incomp


matrixplot(list_tramadol_10.missing_MAR_2, cex.axis = 0.5, interactive = F)

matrixplot(list_tramadol_20.missing_MAR_2, cex.axis = 0.5, interactive = F)

matrixplot(list_tramadol_30.missing_MAR_2, cex.axis = 0.5, interactive = F)

matrixplot(list_tramadol_40.missing_MAR_2, cex.axis = 0.5, interactive = F)

matrixplot(list_tramadol_50.missing_MAR_2, cex.axis = 0.5, interactive = F)
```

```{r}

list_tramadol_10.missing_MNAR_2<- produce_NA(list_tramadol[,9:13], mechanism="MNAR", perc.missing = 0.1,seed = 123)$data.incomp

list_tramadol_20.missing_MNAR_2<- produce_NA(list_tramadol[,9:13], mechanism="MNAR", perc.missing = 0.2,seed = 123)$data.incomp

list_tramadol_30.missing_MNAR_2<- produce_NA(list_tramadol[,9:13], mechanism="MNAR", perc.missing = 0.3,seed = 123)$data.incomp

list_tramadol_40.missing_MNAR_2<- produce_NA(list_tramadol[,9:13], mechanism="MNAR", perc.missing = 0.4,seed = 123)$data.incomp

list_tramadol_50.missing_MNAR_2<- produce_NA(list_tramadol[,9:13], mechanism="MNAR", perc.missing = 0.5,seed = 123)$data.incomp


matrixplot(list_tramadol_10.missing_MNAR_2, cex.axis = 0.5, interactive = F)

matrixplot(list_tramadol_20.missing_MNAR_2, cex.axis = 0.5, interactive = F)

matrixplot(list_tramadol_30.missing_MNAR_2, cex.axis = 0.5, interactive = F)

matrixplot(list_tramadol_40.missing_MNAR_2, cex.axis = 0.5, interactive = F)

matrixplot(list_tramadol_50.missing_MNAR_2, cex.axis = 0.5, interactive = F)
```


```{r}
impute<-impute(formula=group_6~group_1+group_2+group_3+group_4+group_5,data = cbind(list_tramadol_control,list_tramadol_50.missing_MCAR_2)[,c(1:5,6)])


cbind(impute,list_tramadol_50.missing_MCAR_2[,1])
```


